/* https://en.wikipedia.org/wiki/List_of_country_calling_codes */

module.exports = {
  name: 'callingCode',
  title: 'Calling Code',
  description: 'An international telephone calling code defined by the ITU-T in standards E.123 and E.164.',
  values: [
    /* Zone 1: North American Numbering Plan */
    { value: '1', description: 'Canada, United States and North American Numbering Plan (NANP)' },

    /* Zone 2: Mostly Africa */
    { value: '20', description: 'Egypt' },
    { value: '211', description: 'South Sudan' },
    { value: '212', description: 'Morocco' },
    { value: '213', description: 'Algeria' },
    { value: '216', description: 'Tunisia' },
    { value: '218', description: 'Libya' },
    { value: '220', description: 'Gambia' },
    { value: '221', description: 'Senegal' },
    { value: '222', description: 'Mauritania' },
    { value: '223', description: 'Mali' },
    { value: '224', description: 'Guinea' },
    { value: '225', description: 'Ivory Coast' },
    { value: '226', description: 'Burkina Faso' },
    { value: '227', description: 'Niger' },
    { value: '228', description: 'Togo' },
    { value: '229', description: 'Benin' },
    { value: '230', description: 'Mauritius' },
    { value: '231', description: 'Liberia' },
    { value: '232', description: 'Sierra Leone' },
    { value: '233', description: 'Ghana' },
    { value: '234', description: 'Nigeria' },
    { value: '235', description: 'Chad' },
    { value: '236', description: 'Central African Republic' },
    { value: '237', description: 'Cameroon' },
    { value: '238', description: 'Cape Verde' },
    { value: '239', description: 'São Tomé and Príncipe' },
    { value: '240', description: 'Equatorial Guinea' },
    { value: '241', description: 'Gabon' },
    { value: '242', description: 'Republic of the Congo' },
    { value: '243', description: 'Democratic Republic of the Congo' },
    { value: '244', description: 'Angola' },
    { value: '245', description: 'Guinea-Bissau' },
    { value: '246', description: 'British Indian Ocean Territory' },
    { value: '247', description: 'Ascension Island' },
    { value: '248', description: 'Seychelles' },
    { value: '249', description: 'Sudan' },
    { value: '250', description: 'Rwanda' },
    { value: '251', description: 'Ethiopia' },
    { value: '252', description: 'Somalia' },
    { value: '253', description: 'Djibouti' },
    { value: '254', description: 'Kenya' },
    { value: '255', description: 'Tanzania and Zanzibar' },
    { value: '256', description: 'Uganda' },
    { value: '257', description: 'Burundi' },
    { value: '258', description: 'Mozambique' },
    { value: '260', description: 'Zambia' },
    { value: '261', description: 'Madagascar' },
    { value: '262', description: 'Réunion and Moyette' },
    { value: '263', description: 'Zimbabwe' },
    { value: '264', description: 'Namibia' },
    { value: '265', description: 'Malawi' },
    { value: '266', description: 'Lesotho' },
    { value: '267', description: 'Botswana' },
    { value: '268', description: 'Eswatini' },
    { value: '269', description: 'Comoros' },
    { value: '27', description: 'South Africa' },
    { value: '290', description: 'Saint Helena and Tristan da Cunha' },
    { value: '291', description: 'Eritrea' },
    { value: '297', description: 'Aruba' },
    { value: '298', description: 'Faroe Islands' },
    { value: '299', description: 'Greenland' },

    /* Zones 3-4: Europe */
    { value: '30', description: 'Greece' },
    { value: '31', description: 'Netherlands' },
    { value: '32', description: 'Belgium' },
    { value: '33', description: 'France' },
    { value: '34', description: 'Spain' },
    { value: '350', description: 'Gibraltar' },
    { value: '351', description: 'Portugal' },
    { value: '352', description: 'Luxembourg' },
    { value: '353', description: 'Ireland' },
    { value: '354', description: 'Iceland' },
    { value: '355', description: 'Albania' },
    { value: '356', description: 'Malta' },
    { value: '357', description: 'Cyprus' },
    { value: '358', description: 'Finland and Åland Islands' },
    { value: '359', description: 'Bulgaria' },
    { value: '36', description: 'Hungary' },
    { value: '370', description: 'Lithuania' },
    { value: '371', description: 'Latvia' },
    { value: '372', description: 'Estonia' },
    { value: '373', description: 'Moldova' },
    { value: '374', description: 'Armenia and Artsakh' },
    { value: '375', description: 'Belarus' },
    { value: '376', description: 'Andorra' },
    { value: '377', description: 'Monaco' },
    { value: '378', description: 'San Marino' },
    { value: '380', description: 'Ukraine' },
    { value: '381', description: 'Serbia' },
    { value: '382', description: 'Montenegro' },
    { value: '383', description: 'Kosovo' },
    { value: '385', description: 'Croatia' },
    { value: '386', description: 'Slovenia' },
    { value: '387', description: 'Bosnia and Herzegovina' },
    { value: '389', description: 'North Macedonia' },
    { value: '39', description: 'Italy and Vatican City' },
    { value: '40', description: 'Romania' },
    { value: '41', description: ' Switzerland' },
    { value: '420', description: 'Czech Republic' },
    { value: '421', description: 'Slovakia' },
    { value: '423', description: 'Liechtenstein' },
    { value: '43', description: 'Austria' },
    { value: '44', description: 'United Kingdom, Guernsey, Jersey and Isle of Man' },
    { value: '45', description: 'Denmark' },
    { value: '46', description: 'Sweden' },
    { value: '47', description: 'Norway and Svalbard' },
    { value: '48', description: 'Poland' },
    { value: '49', description: 'Germany' },

    /* Zone 5: Americas outside the NANP */
    { value: '500', description: 'Falkland Islands, South Georgia and the South Sandwich Islands' },
    { value: '501', description: 'Belize' },
    { value: '502', description: 'Guatemala' },
    { value: '503', description: 'El Salvador' },
    { value: '504', description: 'Honduras' },
    { value: '505', description: 'Nicaragua' },
    { value: '506', description: 'Costa Rica' },
    { value: '507', description: 'Panama' },
    { value: '508', description: 'Saint-Pierre and Miquelon' },
    { value: '509', description: 'Haiti' },
    { value: '51', description: 'Peru' },
    { value: '52', description: 'Mexico' },
    { value: '53', description: 'Cuba' },
    { value: '54', description: 'Argentina' },
    { value: '55', description: 'Brazil' },
    { value: '56', description: 'Chile' },
    { value: '57', description: 'Colombia' },
    { value: '58', description: 'Venezuela' },
    { value: '590', description: 'Guadeloupe, Saint Barthélemy and Saint Martin' },
    { value: '591', description: 'Bolivia' },
    { value: '592', description: 'Guyana' },
    { value: '593', description: 'Ecuador' },
    { value: '594', description: 'French Guiana' },
    { value: '595', description: 'Paraguay' },
    { value: '596', description: 'Martinique' },
    { value: '597', description: 'Suriname' },
    { value: '598', description: 'Uruguay' },
    { value: '599', description: 'Sint Eustatius, Saba, Bonaire, Curaçao' },

    /* Zone 6: Southeast Asia and Oceania */
    { value: '60', description: 'Malaysia' },
    { value: '61', description: 'Australia, Cocos Islands and Christmas Island' },
    { value: '62', description: 'Indonesia' },
    { value: '63', description: 'Philippines' },
    { value: '64', description: 'New Zealand and Pitcairn Islands' },
    { value: '65', description: 'Singapore' },
    { value: '66', description: 'Thailand' },
    { value: '670', description: 'East Timor' },
    { value: '672', description: 'Australian External Territories, Australian Antarctic Territory and Norfolk Island' },
    { value: '673', description: 'Brunei' },
    { value: '674', description: 'Nauru' },
    { value: '675', description: 'Papua New Guinea' },
    { value: '676', description: 'Tonga' },
    { value: '677', description: 'Solomon Islands' },
    { value: '678', description: 'Vanuatu' },
    { value: '679', description: 'Fiji' },
    { value: '680', description: 'Palau' },
    { value: '681', description: 'Wallis and Futuna' },
    { value: '682', description: 'Cook Islands' },
    { value: '683', description: 'Niue' },
    { value: '685', description: 'Samoa' },
    { value: '686', description: 'Kiribati' },
    { value: '687', description: 'New Caledonia' },
    { value: '688', description: 'Tuvalu' },
    { value: '689', description: 'French Polynesia' },
    { value: '690', description: 'Tokelau' },
    { value: '691', description: 'Federated States of Micronesia' },
    { value: '692', description: 'Marshall Islands' },

    /* Zone 7: Parts of the former Soviet Union */
    { value: '7', description: 'Russia, Kazakhstan and Abkhazia' },

    /* Zone 8: East Asia and special services */
    { value: '800', description: 'International Freephone (UIFN)' },
    { value: '808', description: 'Shared Cost Services' },
    { value: '81', description: 'Japan' },
    { value: '82', description: 'South Korea' },
    { value: '84', description: 'Vietnam' },
    { value: '850', description: 'North Korea' },
    { value: '852', description: 'Hong Kong' },
    { value: '853', description: 'Macau' },
    { value: '855', description: 'Cambodia' },
    { value: '856', description: 'Laos' },
    { value: '86', description: 'China' },
    { value: '870', description: 'Inmarsat "SNAC" Service' },
    { value: '875', description: 'Maritime Mobile Service' },
    { value: '876', description: 'Maritime Mobile Service' },
    { value: '877', description: 'Maritime Mobile Service' },
    { value: '878', description: 'Universal Personal Telecommunications Services' },
    { value: '879', description: 'National Non-Commercial Purposes' },
    { value: '880', description: 'Bangladesh' },
    { value: '881', description: 'Global Mobile Satellite System' },
    { value: '882', description: 'International Networks' },
    { value: '883', description: 'International Networks' },
    { value: '886', description: 'Taiwan' },
    { value: '888', description: 'Telecommunications for Disaster Relief by OCHA' },

    /* Zone 9: Mostly Middle East and parts of southern Asia */
    { value: '90', description: 'Turkey and Northern Cyprus' },
    { value: '91', description: 'India' },
    { value: '92', description: 'Pakistan, Azad Kashmir and Gilgit Baltistan' },
    { value: '93', description: 'Afghanistan' },
    { value: '94', description: 'Sri Lanka' },
    { value: '95', description: 'Myanmar' },
    { value: '960', description: 'Maldives' },
    { value: '961', description: 'Lebanon' },
    { value: '962', description: 'Jordan' },
    { value: '963', description: 'Syria' },
    { value: '964', description: 'Iraq' },
    { value: '965', description: 'Kuwait' },
    { value: '966', description: 'Saudi Arabia' },
    { value: '967', description: 'Yemen' },
    { value: '968', description: 'Oman' },
    { value: '970', description: 'Palestine' },
    { value: '971', description: 'United Arab Emirates' },
    { value: '972', description: 'Israel' },
    { value: '973', description: 'Bahrain' },
    { value: '974', description: 'Qatar' },
    { value: '975', description: 'Bhutan' },
    { value: '976', description: 'Mongolia' },
    { value: '977', description: 'Nepal' },
    { value: '979', description: 'International Premium Rate Service' },
    { value: '98', description: 'Iran' },
    { value: '991', description: 'International Telecommunications Public Correspondence Service Trial (ITPCS)' },
    { value: '992', description: 'Tajikistan' },
    { value: '993', description: 'Turkmenistan' },
    { value: '994', description: 'Azerbaijan' },
    { value: '995', description: 'Georgia, South Ossetia and Abkhazia' },
    { value: '996', description: 'Kyrgyzstan' },
    { value: '998', description: 'Uzbekistan' },
    { value: '999', description: 'Global service' }
  ]
}
