module.exports = {
  DOC_STORE_DOCUMENT_WAS_REPLACED: 'DOC_STORE_DOCUMENT_WAS_REPLACED',
  DOC_STORE_DOCUMENT_WAS_CREATED: 'DOC_STORE_DOCUMENT_WAS_CREATED',
  DOC_STORE_DOCUMENT_WAS_DELETED: 'DOC_STORE_DOCUMENT_WAS_DELETED',
  DOC_STORE_DOCUMENT_DID_NOT_EXIST: 'DOC_STORE_DOCUMENT_DID_NOT_EXIST'
}
