/* https://en.wikipedia.org/wiki/ISO_4217 */

module.exports = {
  name: 'currencyCode',
  title: 'Currency Code',
  description: 'A currency designator from ISO 4217.',
  values: [
    { value: 'AED', description: 'United Arab Emirates Dirham' },
    { value: 'AFN', description: 'Afghan Afghani' },
    { value: 'ALL', description: 'Albanian Lek' },
    { value: 'AMD', description: 'Armenian Dram' },
    { value: 'ANG', description: 'Netherlands Antillean Guilder' },
    { value: 'AOA', description: 'Angolan Kwanza' },
    { value: 'ARS', description: 'Argentine Peso' },
    { value: 'AUD', description: 'Australian Dollar' },
    { value: 'AWG', description: 'Aruban Florin' },
    { value: 'AZN', description: 'Azerbaijani Manat' },
    { value: 'BAM', description: 'Bosnia and Herzegovina Convertible Mark' },
    { value: 'BBD', description: 'Barbados Dollar' },
    { value: 'BDT', description: 'Bangladeshi Taka' },
    { value: 'BGN', description: 'Bulgarian Lev' },
    { value: 'BHD', description: 'Bahraini Dinar' },
    { value: 'BIF', description: 'Burundian Franc' },
    { value: 'BMD', description: 'Bermudian Dollar' },
    { value: 'BND', description: 'Brunei Dollar' },
    { value: 'BOB', description: 'Boliviano' },
    { value: 'BOV', description: 'Bolivian Mvdol (funds code)' },
    { value: 'BRL', description: 'Brazilian Real' },
    { value: 'BSD', description: 'Bahamian Dollar' },
    { value: 'BTN', description: 'Bhutanese Ngultrum' },
    { value: 'BWP', description: 'Botswana Pula' },
    { value: 'BYN', description: 'Belarusian Ruble' },
    { value: 'BZD', description: 'Belize Dollar' },
    { value: 'CAD', description: 'Canadian Dollar' },
    { value: 'CDF', description: 'Congolese Franc' },
    { value: 'CHE', description: 'WIR Euro' },
    { value: 'CHF', description: 'Swiss Franc' },
    { value: 'CHW', description: 'WIR Franc' },
    { value: 'CLF', description: 'Unidad de Fomento (funds code)' },
    { value: 'CLP', description: 'Chilean Peso' },
    { value: 'CNY', description: 'Renminbi (Chinese) Yuan' },
    { value: 'COP', description: 'Colombian Peso' },
    { value: 'COU', description: 'Unidad de Valor Real (UVR)' },
    { value: 'CRC', description: 'Costa Rican Colon' },
    { value: 'CUC', description: 'Cuban convertible Peso' },
    { value: 'CUP', description: 'Cuban Peso' },
    { value: 'CVE', description: 'Cape Verdean Escudo' },
    { value: 'CZK', description: 'Czech Koruna' },
    { value: 'DJF', description: 'Djiboutian Franc' },
    { value: 'DKK', description: 'Danish Krone' },
    { value: 'DOP', description: 'Dominican Peso' },
    { value: 'DZD', description: 'Algerian Dinar' },
    { value: 'EGP', description: 'Egyptian Pound' },
    { value: 'ERN', description: 'Eritrean Nakfa' },
    { value: 'ETB', description: 'Ethiopian Birr' },
    { value: 'EUR', description: 'Euro' },
    { value: 'FJD', description: 'Fiji Dollar' },
    { value: 'FKP', description: 'Falkland Islands Pound' },
    { value: 'GBP', description: 'Pound Sterling' },
    { value: 'GEL', description: 'Georgian Lari' },
    { value: 'GHS', description: 'Ghanaian Cedi' },
    { value: 'GIP', description: 'Gibraltar Pound' },
    { value: 'GMD', description: 'Gambian Dalasi' },
    { value: 'GNF', description: 'Guinean Franc' },
    { value: 'GTQ', description: 'Guatemalan Quetzal' },
    { value: 'GYD', description: 'Guyanese Dollar' },
    { value: 'HKD', description: 'Hong Kong Dollar' },
    { value: 'HNL', description: 'Honduran Lempira' },
    { value: 'HRK', description: 'Croatian Kuna' },
    { value: 'HTG', description: 'Haitian Gourde' },
    { value: 'HUF', description: 'Hungarian Forint' },
    { value: 'IDR', description: 'Indonesian Rupiah' },
    { value: 'ILS', description: 'Israeli New Shekel' },
    { value: 'INR', description: 'Indian Rupee' },
    { value: 'IQD', description: 'Iraqi Dinar' },
    { value: 'IRR', description: 'Iranian Rial' },
    { value: 'ISK', description: 'Icelandic Króna' },
    { value: 'JMD', description: 'Jamaican Dollar' },
    { value: 'JOD', description: 'Jordanian Dinar' },
    { value: 'JPY', description: 'Japanese Yen' },
    { value: 'KES', description: 'Kenyan Shilling' },
    { value: 'KGS', description: 'Kyrgyzstani Som' },
    { value: 'KHR', description: 'Cambodian Riel' },
    { value: 'KMF', description: 'Comoro Franc' },
    { value: 'KPW', description: 'North Korean Won' },
    { value: 'KRW', description: 'South Korean Won' },
    { value: 'KWD', description: 'Kuwaiti Dinar' },
    { value: 'KYD', description: 'Cayman Islands Dollar' },
    { value: 'KZT', description: 'Kazakhstani Tenge' },
    { value: 'LAK', description: 'Lao Kip' },
    { value: 'LBP', description: 'Lebanese Pound' },
    { value: 'LKR', description: 'Sri Lankan Rupee' },
    { value: 'LRD', description: 'Liberian Dollar' },
    { value: 'LSL', description: 'Lesotho Loti' },
    { value: 'LYD', description: 'Libyan Dinar' },
    { value: 'MAD', description: 'Moroccan Dirham' },
    { value: 'MDL', description: 'Moldovan Leu' },
    { value: 'MGA', description: 'Malagasy Ariary' },
    { value: 'MKD', description: 'Macedonian Denar' },
    { value: 'MMK', description: 'Myanmar Kyat' },
    { value: 'MNT', description: 'Mongolian Tögrög' },
    { value: 'MOP', description: 'Macanese Pataca' },
    { value: 'MRU', description: 'Mauritanian Ouguiya' },
    { value: 'MUR', description: 'Mauritian Rupee' },
    { value: 'MVR', description: 'Maldivian Rufiyaa' },
    { value: 'MWK', description: 'Malawian Kwacha' },
    { value: 'MXN', description: 'Mexican Peso' },
    { value: 'MXV', description: 'Mexican Unidad de Inversion (UDI)' },
    { value: 'MYR', description: 'Malaysian Ringgit' },
    { value: 'MZN', description: 'Mozambican Metical' },
    { value: 'NAD', description: 'Namibian Dollar' },
    { value: 'NGN', description: 'Nigerian Naira' },
    { value: 'NIO', description: 'Nicaraguan Córdoba' },
    { value: 'NOK', description: 'Norwegian Krone' },
    { value: 'NPR', description: 'Nepalese Rupee' },
    { value: 'NZD', description: 'New Zealand Dollar' },
    { value: 'OMR', description: 'Omani Rial' },
    { value: 'PAB', description: 'Panamanian Balboa' },
    { value: 'PEN', description: 'Peruvian Sol' },
    { value: 'PGK', description: 'Papua New Guinean Kina' },
    { value: 'PHP', description: 'Philippine Peso' },
    { value: 'PKR', description: 'Pakistani Rupee' },
    { value: 'PLN', description: 'Polish Złoty' },
    { value: 'PYG', description: 'Paraguayan Guaraní' },
    { value: 'QAR', description: 'Qatari Riyal' },
    { value: 'RON', description: 'Romanian Leu' },
    { value: 'RSD', description: 'Serbian Dinar' },
    { value: 'RUB', description: 'Russian Ruble' },
    { value: 'RWF', description: 'Rwandan Franc' },
    { value: 'SAR', description: 'Saudi Riyal' },
    { value: 'SBD', description: 'Solomon Islands Dollar' },
    { value: 'SCR', description: 'Seychelles Rupee' },
    { value: 'SDG', description: 'Sudanese Pound' },
    { value: 'SEK', description: 'Swedish Krona/Kronor' },
    { value: 'SGD', description: 'Singapore Dollar' },
    { value: 'SHP', description: 'Saint Helena Pound' },
    { value: 'SLL', description: 'Sierra Leonean Leone' },
    { value: 'SOS', description: 'Somali Shilling' },
    { value: 'SRD', description: 'Surinamese Dollar' },
    { value: 'SSP', description: 'South Sudanese Pound' },
    { value: 'STN', description: 'São Tomé and Príncipe Dobra' },
    { value: 'SVC', description: 'Salvadoran Colón' },
    { value: 'SYP', description: 'Syrian Pound' },
    { value: 'SZL', description: 'Swazi Lilangeni' },
    { value: 'THB', description: 'Thai Baht' },
    { value: 'TJS', description: 'Tajikistani Somoni' },
    { value: 'TMT', description: 'Turkmenistan Manat' },
    { value: 'TND', description: 'Tunisian Dinar' },
    { value: 'TOP', description: 'Tongan Paʻanga' },
    { value: 'TRY', description: 'Turkish Lira' },
    { value: 'TTD', description: 'Trinidad and Tobago Dollar' },
    { value: 'TWD', description: 'New Taiwan Dollar' },
    { value: 'TZS', description: 'Tanzanian Shilling' },
    { value: 'UAH', description: 'Ukrainian Hryvnia' },
    { value: 'UGX', description: 'Ugandan Shilling' },
    { value: 'USD', description: 'United States Dollar' },
    { value: 'USN', description: 'United States Dollar (next day)' },
    { value: 'UYI', description: 'Uruguay Peso en Unidades Indexadas (URUIURUI)' },
    { value: 'UYU', description: 'Uruguayan Peso' },
    { value: 'UYW', description: 'Unidad Previsional' },
    { value: 'UZS', description: 'Uzbekistan Som' },
    { value: 'VES', description: 'Venezuelan Bolívar Soberano' },
    { value: 'VND', description: 'Vietnamese Dồng' },
    { value: 'VUV', description: 'Vanuatu Vatu' },
    { value: 'WST', description: 'Samoan Tala' },
    { value: 'XAF', description: 'CFA franc BEAC' },
    { value: 'XAG', description: 'Silver (one troy ounce)' },
    { value: 'XAU', description: 'Gold (one troy ounce)' },
    { value: 'XBA', description: 'European Composite Unit (EURCO)' },
    { value: 'XBB', description: 'European Monetary Unit (E.M.U.-6)' },
    { value: 'XBC', description: 'European Unit of Account 9 (E.U.A.-9)' },
    { value: 'XBD', description: 'European Unit of Account 17 (E.U.A.-17)' },
    { value: 'XCD', description: 'East Caribbean Dollar' },
    { value: 'XDR', description: 'Special Drawing Rights' },
    { value: 'XOF', description: 'CFA Franc BCEAO' },
    { value: 'XPD', description: 'Palladium (one troy ounce)' },
    { value: 'XPF', description: 'CFP Franc (franc Pacifique)' },
    { value: 'XPT', description: 'Platinum (one troy ounce)' },
    { value: 'XSU', description: 'SUCRE' },
    { value: 'XTS', description: 'Code Reserved for Testing' },
    { value: 'XUA', description: 'ADB Unit of Account' },
    { value: 'XXX', description: 'No Currency' },
    { value: 'YER', description: 'Yemeni Rial' },
    { value: 'ZAR', description: 'South African Rand' },
    { value: 'ZMW', description: 'Zambian Kwacha' },
    { value: 'ZWL', description: 'Zimbabwean Dollar' }
  ]
}
