name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Setup Mongo database
      run: |
        docker run -d --name test-mongo-with-sengi -p 127.0.0.1:27017:27017 \
          -e MONGO_INITDB_ROOT_USERNAME=sengi \
          -e MONGO_INITDB_ROOT_PASSWORD=sengi \
          mongo:4.2.9
    - name: Setup Dynamo database
      run: docker run -d -p 8000:8000 amazon/dynamodb-local:1.13.4
    - name: Install deps
      run: npm ci
    - name: Build interfaces library
      run: |
        cd workspaces/sengi-interfaces
        npm run build
    - name: Test document stores (cosmos)
      run: |
        cd workspaces/sengi-docstore-cosmosdb
        npm run setup
        npm test
        npm run teardown
        npm run build
      env:
        SENGI_COSMOS_URL: ${{ secrets.SENGI_COSMOS_URL }}
        SENGI_COSMOS_KEY: ${{ secrets.SENGI_COSMOS_KEY }}
    - name: Test document stores (dynamodb)
      run: |
        cd workspaces/sengi-docstore-dynamodb
        npm run setup
        npm test
        npm run build
    - name: Test document stores (in-memory)
      run: |
        cd workspaces/sengi-docstore-mem
        npm test
        npm run build
    - name: Test document stores (mongo)
      run: |
        cd workspaces/sengi-docstore-mongodb
        npm test
        npm run build
    - name: Test engine
      run: |
        cd workspaces/sengi-engine
        npm test
        npm run build
    - name: Test express wrapper
      run: |
        cd workspaces/sengi-express
        npm test
        npm run build
